import fs from 'node:fs/promises';
import path from 'node:path';

const projectRoot = process.cwd();
const outDir = path.join(projectRoot, 'public');
const outFile = path.join(outDir, 'env.js');

const supabaseUrl = process.env.SUPABASE_URL ?? '';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY ?? '';

await fs.mkdir(outDir, { recursive: true });

const js = `// This file is generated by scripts/build.mjs\n// Do not commit secrets here. Use SUPABASE_URL and SUPABASE_ANON_KEY env vars.\nwindow.__ENV = window.__ENV || {};\nwindow.__ENV.SUPABASE_URL = ${JSON.stringify(supabaseUrl)};\nwindow.__ENV.SUPABASE_ANON_KEY = ${JSON.stringify(supabaseAnonKey)};\n`;

await fs.writeFile(outFile, js, 'utf8');

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('[build] Missing SUPABASE_URL or SUPABASE_ANON_KEY.');
  console.warn('[build] The app will show a configuration error until you set env vars.');
} else {
  console.log('[build] Wrote public/env.js');
}
